#  兼容关键字与按钮对话打断
# CUDA_VISIBLE_DEVICES=2 uv run src/demo.py --config config/chat_with_egdetts_xingkong3_musetalk5.yaml
# CUDA_VISIBLE_DEVICES=2 nohup uv run src/demo.py --config config/chat_with_egdetts_xingkong3_musetalk5.yaml > ./logs/8020.log 2>&1 &
default:
  logger:
    log_level: "INFO"
  service:
    host: "0.0.0.0"
    port: 8020
    cert_file: "ssl_certs/localhost.crt"
    cert_key: "ssl_certs/localhost.key"
  chat_engine:
    model_root: "models"
    concurrent_limit: 5
    handler_search_path:
      - "src/handlers"
    handler_configs:
      RtcClient:
        module: client/rtc_client/client_handler_rtc5
        # max time a session will last for
        connection_ttl: 3600
      SileroVad:
        module: vad/silerovad/vad_handler_silero3
        speaking_threshold: 0.5
        start_delay: 2048
        end_delay: 5000
        buffer_look_back: 5000
        speech_padding: 512
      SenseVoice:
        enabled: True
        module: asr/sensevoice/asr_handler_sensevoice5
        model_name: "iic/SenseVoiceSmall"
      Edge_TTS:
        enabled: True
        module: tts/edgetts/tts_handler_edgetts5
        voice: "zh-CN-XiaoxiaoNeural"

      # CosyVoice:
      #   enabled: True
      #   module: tts/bailian_tts/tts_handler_cosyvoice_bailian
      #   # voice: "longyingxiao_v3"  年轻小女生
      #   voice: "longyingling_v3"  # 优雅知性女
      #   # voice: "longanzhi_v3"  # 成熟稳重男
      #   # voice: "longanyang"
      #   # model_name: "cosyvoice-v1"
      #   model_name: "cosyvoice-v3-flash"
      #   # api_key: "sk-10405643d30443d8b641e0771ed56d2f" # default=os.getenv("DASHSCOPE_API_KEY")
      #   # api_key: "sk-a588f70e9a614e4f87533ff792d2e358"
      #   api_key: "sk-5f2d36a950e1406aa9a15b9bcb8b4616"


      LLMWorkflowStreaming:
        enabled: True
        module: llm/xingkong3/llm_handler_xingkong3_streaming4
        api_url: "http://188.18.18.106:5001/v1/workflows/run"  # workflows
        # api_url: "http://188.18.18.106:5001/v1/chat-messages"  # chat
        api_key: "app-Mbzurid5vkLrmjKuo4rERLDO"  #app-BgSVnRI9NnpUpO5DJFTlx1P3 #chat   ；app-Mbzurid5vkLrmjKuo4rERLDO #Workflow
        user_id: "abc-123"
        timeout: 30

      # MiniCPM-o:
      #   enabled: True
      #   module: llm/minicpm/llm_handler_minicpm
      #   model_name: "MiniCPM-o-2_6"
      #   # model_name: "MiniCPM-o-2_6-int4"
      #   voice_prompt: "你不是通义千问，你不是阿里云，你是一名由竞业达开发的数字老师。用简短的两三句对话来回答用户的问题，并在对话内容中加入合适的标点符号，不需要讨论标点符号相关的内容。" #模仿输入音频中的声音特征。你不是通义千问，你不是阿里云，你是一名由竞业达开发的数字老师。用简短的两三句对话来回答用户的问题，并在对话内容中加入合适的标点符号，不需要讨论标点符号相关的内容。
      #   assistant_prompt: ""
      #   enable_video_input: True
      #   skip_video_frame: 2

      AvatarMusetalk:
        module: avatar/musetalk/avatar_handler_musetalk42
        fps: 15  # Video frame rate (output_audio_sample_rate 24000;Video frame rate:15、16、20、24、25)
        batch_size: 4 # Batch processing frame count, must be greater than 2
        # avatar_video_path: "src/handlers/avatar/musetalk/MuseTalk/data/video/wangshuang480p.mp4"  # wang形象
        # avatar_video_path: "src/handlers/avatar/musetalk/MuseTalk/data/video/man480p.mp4" #weiyanmin
        # avatar_video_path: "src/handlers/avatar/musetalk/MuseTalk/data/video/xw126.mp4"  #白色背景
        avatar_video_path: "src/handlers/avatar/musetalk/MuseTalk/data/video/wei_128_1.mp4"   # 蓝色背景
        # 可灵ai定制xiaofei480p"/opt/jyd01/liushiguo/OpenAvatarChat_test/src/handlers/avatar/musetalk/MuseTalk/data/video/001-720p.mp4"

        avatar_model_dir: "models/musetalk/avatar_model"  # Default avatar model directory
        force_create_avatar: false  # Whether to force regenerate digital human data
        debug: false  # Whether to enable debug mode
        multi_thread_inference: true  # true: use 2 threads to inference (unet, vae), false: use single-thread to inference
        debug_save_handler_audio: false  # Whether to save audio frames
        # debug_replay_speech_id: "speech-d9o18xrugl6-1"  # Speech ID for replay

        
      # LiteAvatar:
      #   module: avatar/liteavatar/avatar_handler_liteavatar
      #   # 默认
      #   # avatar_name: 20250408/sample_data
      #   # 女老师
      #   # avatar_name: 20250612/P17L8MoMPLjyWLWn7-jCrnAw
      #   # 男帅哥
      #   # avatar_name: 20250408/P1tnueW7ufnZuEVix6rmAOzw
      #   # 男老师
      #   # avatar_name: 20250612/P1GHtv7jDegag9hgcPFAW7Ng
      #   # 男青年
      #   # avatar_name: 20250612/P1PNFMLjxwu9Cbi2nyK5yoaA
      #   # 灰色背景女老师
      #   avatar_name: 20250612/P18qnW9QV47heC5q0hNWUiqQ
      #   fps: 25
      #   debug: false
      #   enable_fast_mode: false
      #   use_gpu: true

